CREATE TABLE workflow_instance (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR2(100) NOT NULL,
    business_key VARCHAR2(100) NOT NULL,
    current_state VARCHAR2(50) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE workflow_action (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_instance_id NUMBER(19, 0) NOT NULL,
    payment_id VARCHAR2(100) NOT NULL,
    action_name VARCHAR2(100) NOT NULL,
    state VARCHAR2(100) NOT NULL,
    action_order NUMBER(10, 0) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    retry_count NUMBER(10, 0) DEFAULT 0 NOT NULL,
    error_code VARCHAR2(100),
    error_message CLOB,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_workflow_action_instance
        FOREIGN KEY (workflow_instance_id)
        REFERENCES workflow_instance (id)
);

CREATE TABLE retry_configuration (
    action_name VARCHAR2(100) PRIMARY KEY,
    max_retry NUMBER(10, 0) NOT NULL,
    retry_interval_seconds NUMBER(10, 0) NOT NULL
);

CREATE INDEX idx_workflow_instance_business_key
    ON workflow_instance (business_key);

CREATE INDEX idx_workflow_action_instance
    ON workflow_action (workflow_instance_id);

INSERT INTO retry_configuration (action_name, max_retry, retry_interval_seconds)
VALUES ('REQUEST_VALIDATION', 0, 0);

INSERT INTO retry_configuration (action_name, max_retry, retry_interval_seconds)
VALUES ('FIRCO_SCREENING', 3, 2);

INSERT INTO retry_configuration (action_name, max_retry, retry_interval_seconds)
VALUES ('PAYMENT_POSTING', 3, 2);

INSERT INTO retry_configuration (action_name, max_retry, retry_interval_seconds)
VALUES ('ACCOUNTING', 3, 2);

INSERT INTO retry_configuration (action_name, max_retry, retry_interval_seconds)
VALUES ('NOTIFICATION', 3, 2);
