package com.company.workflow.state;

public enum WorkflowEvent {
    START_PAYMENT,
    REQUEST_VALIDATION_SUCCESS,
    REQUEST_VALIDATION_FAILED,
    FIRCO_SCREENING_SUCCESS,
    FIRCO_SCREENING_FAILED,
    PAYMENT_POSTING_SUCCESS,
    PAYMENT_POSTING_FAILED,
    ACCOUNTING_SUCCESS,
    ACCOUNTING_FAILED,
    NOTIFICATION_SUCCESS,
    NOTIFICATION_FAILED,
    RETRY,
    FAIL
}
