spring:
  application:
    name: workflow-orchestration
  datasource:
    url: jdbc:mysql://localhost:3306/ORCLPDB1
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 9099

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000

workflow:
  definitions:
    workflow-payment-processing-workflow:
      actions:
        - REQUEST_VALIDATION
        - FIRCO_SCREENING
        - PAYMENT_POSTING
        - ACCOUNTING
        - NOTIFICATION

mock:
  actions:
    payment-posting-success-probability: 0.75
    accounting-success-probability: 0.9
    notification-success-probability: 0.95
    firco-approved-probability: 0.85
    firco-rejected-probability: 0.05
